### ISSUE TITLE
SilverStripe Cloud Platform Compatibility

### ISSUE THREAD

**Issue by thats4shaw** [Firesphere/silverstripe-solr-search#127]
SCP requires Solr to run under webdav mode like CWP which is mentioned in https://github.com/Firesphere/silverstripe-solr-search/issues/47.

SCP using https://github.com/silverstripe/silverstripe-fulltextsearch also required a `remotepath` config value that looks something like this `/opt/bitnami/apache-solr/solr`.  It's mentioned in the docs here - https://github.com/silverstripe/silverstripe-fulltextsearch/blob/afc6364d22d2d2f7d811d791b0bfdb24c677930f/docs/en/03_configuration.md.  If webdav support was added this would likely also need looking at too.

Thought this was worth documenting for anyone else that is flirting with the idea of migrating.

**Comment by Firesphere** [comment]
A webdav store is indeed something I did consider, but I don't have the time for it right now.

I'm open to Pull Requests though, I don't think it's hard to accomplish using Guzzle, but I'm happily proven wrong on that :D

**Comment by Firesphere** [comment]
I've taken this issue in to consideration. My thought is, the WebDav store as used by CWP and/or SCP should be a separate module. It is a requirement very specific for SilverStripe based PaaS. Therefore, my feeling is, we as a community should not invest in that, I feel this responsibility lies on SilverStripe. The Interface is readily available to support this.

**Comment by chillu** [comment]
Both CWP and SCP work with a custom Solr PHP proxy script which exposes custom `/config` endpoints. This proxy isn't open sourced, and is a hack to avoid a) using WebDAV and b) allow *some* configuration by developers in a shared Solr environment. https://github.com/silverstripe/cwp-search/blob/master/src/Solr/CwpSolrConfigStore.php#L59. Neither of these platforms is using WebDAV.

That being said, I think Simon's argument is the same here - it's very specific to our platforms. Ideally any interfaces in this module take this use case into account. So the ability to "upload a config file" to Solr through various means. Looks like that's already in place through the `ConfigStore->uploadFile()` API which was taken on from the original module: https://github.com/Firesphere/silverstripe-solr-search/blob/b1e4838132e7f06f526a56b466d195ae48d48ae7/src/Interfaces/ConfigStore.php#L22

**Comment by Firesphere** [comment]
As @chillu said, CWP and SCP are very SilverStripe hosted specific.

The methods are available in the Post and File config store, to use this feature. With the exception that it uses Guzzle instead of file_get_contents().

I am unsure how well the PostConfigStore works, but it should work in theory. If not, I strongly suggest a sub-module that adds support instead of integrating vendor-specific features.

Closing this issue for now.
