### ISSUE TITLE
searchQuery::setExclude() doesn't seem to work.

### ISSUE THREAD

**Issue by phptek** [Firesphere/silverstripe-solr-search#143]
**Describe the bug**

`searchQuery::setExclude()` doesn't seem to work.

```
        $exclusions = [
            'SiteTree_ShowInSearch' => 0,
        ];
        $query = SearchQuery::create()
                ->setExclude($exclusions);
```

**To Reproduce**

1). [OK]  Hook up `SiteTree` into a `BaseIndex` subclass, configure and reindex (Tasks).
2). [OK] Ensure the results logic in Page/PageController/Whatever instantiates SearchQuery and sets an exclusion for "SiteTree_ShowInSearch" as per the above
3). [OK] Now toggle and save changes to this field in any Page's "Settings" tab.
4). [FAIL] Regardless of what this value is, the Page's "state" within the results remains unchanged.
5). [FAIL] Regardless of re-running the SolrIndexTask, this Page's "state" within the results remains the same

Additional: Weirdly, if I alter the exclusion thus:

```
'SiteTree_ShowInSearch' => 1,
```

The page in question re-appears. If it's set to zero, the page in question doesn't appear, despite my changing its "ShowInSearch" field value. (But weirder, other pages will still show for different searches.

**Expected behavior**

For changes to "'SiteTree_ShowInSearch" to be more consistent (or for me to understand how it _should_ work better!)

PHP 7.2 + `dev-master#7c78fb8c62618fbd50c926e5772457c827a6f4f0`

**Comment by Firesphere** [comment]
The problem described isn't a failure of `setExclude`, the failure is that the page isn't _removed_ from the index.

Indexing, as opposed to the old module, skips pages/objects that have ShowInSearch set to false.

However, when it's set to true originally, and then later switched to false, the writer does not properly update the index, it leaves the page in the index untouched as opposed to removing it from the index.

Thank you for pointing it out!

**Comment by Firesphere** [comment]
Please note, in the case of a config change, it is advised to clear the index before any re-index. I'll update the docs some time over the weekend if brain cooperates.

**Comment by phptek** [comment]
I did this _many_ times yesterday to do just that:

`#> ./solr-reset.sh start|stop`

```
#!/bin/bash

ACTION="$1"

echo -e "Restarting Solr...\n"

if [[ $ACTION == 'stop' ]]
then
    echo -e "Stopping...\n"

    sudo kill -9 $( ps aux | grep solr | grep java | awk '{ print $2}' )
    rm -rf .solr && mkdir .solr && chmod 777 .solr

    echo -e "Killed process and truncated .solr dir\n"
fi

if [[ $ACTION == 'start' ]]
then
    echo -e "Starting...\n"

    /opt/solr-8.2.0/bin/solr start
    
    echo -e "Restarted Solr\n"
fi

echo -e "Done!\n"
```
