### ISSUE TITLE
Pagination with results-pages >1

### ISSUE THREAD

**Issue by phptek** [Firesphere/silverstripe-solr-search#160]
**Describe the bug**

Paginated results, do not render anything on subsequent pages of results (Page #>1) due to `PaginatedList::setLimitItems()` being passed `true` instead of `false` in SearchResult.php (Passing "false" should allow Solr to deal with pagination rather than Silverstripe).

**To Reproduce**

* Create a list of results for a search-term such that you end up with >1 page of results
* Select page "2" or select "Next"
* Observe empty page, but paginated links are selected/highlighted as expected
* Edit Firesphere\SolrSearch\Results\SearchResult.php:211

Current state:

```
// Do not limit the pagination, it's done at Solr level
$paginated->setLimitItems(true);
```
Working state:

```
// Do not limit the pagination, it's done at Solr level
$paginated->setLimitItems(false);
```

**Expected behavior**

Selecting subsequent pages of results you render results to the screen. See suggested patch above.

**Comment by Firesphere** [comment]
This is a regression from an earlier bug, where the limiting wasn't applied properly.

Thanks!
