### ISSUE TITLE
Debug instructions are incorrect/incomplete

### ISSUE THREAD

**Issue by phptek** [Firesphere/silverstripe-solr-search#163]
As per the docs, (https://firesphere.github.io/solr-docs/07-Debugging.html) the procedure to debug an index are wrong or the logic it references is incorrect.

`BaseIndex::getRawQuery()` is not a method that exists anywhere in the module's codebase. There's a proytected class property `$rawQuery` but no getter/setters for it. The only ref to this method in the module's codebase is in the markdown documents themselves.

**Comment by Firesphere** [comment]
You are correct. This is a bit of not-yet-cleaned-up-code.

The correct reference would be `getQueryTerms`

**Comment by Firesphere** [comment]
Solved in the latest master release
