### ISSUE TITLE
Addition of docs on how to switch default analyzer or copyField

### ISSUE THREAD

**Issue by phptek** [Firesphere/silverstripe-solr-search#165]
**Is your feature request related to a problem? Please describe.**

Using `silverstripe/textextraction` (pdftotext backend) in a custom `DataExtension` applied to `File` classes, any `getContent()` method returning a PDF-to-Text UTF-8 string, raises Java exceptions when that string is > Lucene's default for "String" fields of 32766 bytes during indexing.

>  Exception writing document id SilverStripe\Assets\File-1015 to
the index; possible analysis error: Document contains at least one immense term in
field="File_Content" (whose UTF8 encoding is longer than the max length 32766), all of which were
skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense
term is: '[65, 110.....

**Describe the solution you'd like**

I've worked around this for now, by truncating returned strings from PDF conversions to a length that's acceptable to Lucene's OOTB setup. But the message suggests developers should adjust/correct the analyzer to avoid such problems, as do a slew of SO posts from users of ES and Solr.

Unless I'm missing something (I have before and I will again I'm sorry to say) I am expecting a method or public API that allows me to change the analyzer on a field by field basis. I'm not an expert Solr user by any stretch, so if this is what `addCopyField()` is supposed to do (or something similar, to change Solr's internal field type to permit large text blobs), then some additonal docs on this would be great.

**Describe alternatives you've considered**

See below for current workaround:

```

    /**
     * Used by the search index "File_Content", gets the file content for adding
     * to the index.
     *
     * @return string
     */
    public function getContent()
    {
        $filePath = sprintf('%s/%s', ASSETS_PATH, $this->owner->getFilename());
        $extractor = FileTextExtractor::for_file($filePath);
        $content = $extractor ? trim($extractor->getContent($filePath)) : '';

        // Avoids "immense" string lenth errors from Lucene by limiting what we get out of
        // our FileExtrator implementations:
        //
        // - UTF-8 encodes as x4 single byte chunks of 8 bits.
        // - Lucene's max byte limit is 2^15 (32768) bytes
        // - So we use mb_substr() to calculate the legal length as: 32768/4
        return mb_substr($content, 0, (self::LUCENE_MAX_BYTES / 4), 'UTF-8');
    }
```

**Comment by Firesphere** [comment]
This means the content isn't casted properly.

Steps to fix would be:
- Cast the content to an HTMLText field in the extension
- Optionally, create a custom field that is longer than the Solr defaults

This is not in the module or Solr, but in the implementation of field types Solr uses. The default is `String`, which can not contain as much data as other field types.

Experiments show that casting the field to either Text or HTMLText work for 20-page long PDF's. Although, no promises if that doesn't run out of bytes.

**Comment by Firesphere** [comment]
For analyzer specific issues, please see the Solr docs.

For using a custom `types.ss` file, please see the documentation on how to set a different path to the types.ss file.
