### ISSUE TITLE
Improve existing documentation around "ShowInSearch"

### ISSUE THREAD

**Issue by phptek** [Firesphere/silverstripe-solr-search#176]
Documentation improvement to be made to `03-Usage.md`. Please see the diff here: https://github.com/Firesphere/silverstripe-solr-search/compare/master...phptek:improved-docs

**Comment by phptek** [comment]
Rationale: I feel that a little bit more explanation around the "ShowInSearch" functionality is required. The `ShowInSearch` feature I find incredibly confusing:

* I could (If I wanted to, but shouldn't) add `ShowInSearch` as a `FilterableField` in YML config. But this is undesirable, the reason for which has since been added to the docs (ShowInSearch = 0 objects are _removed_ from the index)
* I could also (If I wanted to, but shouldn't) add `SiteTree_ShowInSearch` as a "Just In Time" exclusion in my index _searching_ logic. But in light of the above point, this doesn't make any sense to do any more. The reason I was doing this, is that is pretty much how we used to do this with the FTS module (Rightly, or wrongly!)
* I was missing context around the use of `SolrIndexJob` which isn't documented anywhere (See also #174). Granted it should be obvious that such a job exists, especially for users who are semi-experienced with the old FTS module. Also - devs used to testing a lot in DEV mode assume things should be auto-updated whenever users hit "Publish", which for `ShowInSearch` isn't the case (Could it be, in `onAfterPublish`?).
* So becuase these objects are removed from the index, then they need to be re-added - by the `SolrIndexJob` (Which simply calls dev/tasks/SolrIndexTask) each time.

**Comment by Firesphere** [comment]
You're free to make that a PR :)

Do note, that ``onAfterPublish` _should_ add a page that has been removed because of ShowInSearch being false again, and not need a full index job again. If this is not the case, please create a separate issue for that?

- The reason for your second point, is that it is pointless to index something that shouldn't show in search. In our opinion, FTS is doing it wrong there. And also, as discussed with others, they all say the ShowInSearch based on the log-in or group status of the member makes a lot more sense.

- SolrIndexJob needs quite a bit of love, I agree

- As above, they should be added again through onAfterPublish, which is also quite well tested. Are you experiencing trouble with that?

**Comment by phptek** [comment]
> The reason for your second point, is that it is pointless to index something that shouldn't show in search

Understood. My point is that _I am able to do it_. I am able to shoot myself in the foot, but essentially not know that I have shot myself in the foot. This could be an experience thing of course, but good docs around this are essential such that other folks don't have to grab around in the dark like I have been doing :-D

> SolrIndexJob needs quite a bit of love, I agree

See updates made to #174 

> As above, they should be added again through onAfterPublish, which is also quite well tested. Are you experiencing trouble with that?

Sigh - it's my setup probably (See point one above). But sure, checking/unchecking "Show in search?" in the CMS,  does not immediately hide/unhide a given page from my search index when running in DEV mode. Am I correct in assuming that it should do? (`onAfterPublish()` suggests that it should).

FYI my simpler YML config now looks like this:

```
Catalyst\MyProject\Search\TRCIndex:
  MyIndex:
    Classes:
      - SilverStripe\CMS\Model\SiteTree
      - SilverStripe\Assets\File
    FulltextFields:
      - Title
      - Content
      - Intro
      - ElementsForSearch
    FilterFields:
      - SubsiteID
      - ClassName
    CopyFields:
      _text:
        - '*'
    DefaultField: _text
```

And simple controller logic looks like this:

```
$exclusions = [
    'File_ClassName' => Image::class,
];
$index = Injector::inst()->create(MyIndexIndex::class);
$query = SearchQuery::create()
        ->setStart($start)
        ->addTerm($terms, [], 0, 0.35)
        ->setRows(self::$results_per_page)
        ->setExclude($exclusions);
$result = $index->doSearch($query);
```

**Comment by phptek** [comment]
[UPDATE] It works _only_ if I have enabled the SolrIndexTask and I wait for _that_ to run. But Save --> Hide From Search --> Publish doesn't work in DEV straight away.

**Comment by Firesphere** [comment]
Okay, that it doesn't work straight away is either a bug, or an issue with pushing it to Solr.

Could you check if you have any dirty classes with IDs? You can check that in the CMS.

**Comment by phptek** [comment]
Yes, there are 4 classes with dirty IDs.

**Comment by Firesphere** [comment]
Hmmm, that sounds like onAfterWrite/onAfterPublish isn't doing it's job properly.

There is a ClearDirtyClasses task you could use to attempt to clear those out

**Comment by phptek** [comment]
I ran the task, which AFAICT, cleared out my dirty IDs, but also emitted an error (Reported in #180).

Regardless, I did the following afterwards, still no dice:

* [OK] Search for keyword
* [OK] Observe desired page apears in results
* [OK] In the CMS, de-select the "Show in search?" checkbox
* [OK] Hit "Publish"
* [FAIL] Observe that the page from step 2 has been removed from the results (Logged in)
* [FAIL] Observe that the page from step 2 has been removed from the results (Incognito)

**Comment by Firesphere** [comment]
Cheers for your report. I'll have a look at what's going on there later when I have time.

**Comment by Firesphere** [comment]
Hi @phptek ,
I think I've identified your problem. The reason is most probably, that the `updateItems` method did not commit immediately. This could lead to results still being in the index for a while, most commonly at least 60 seconds. But it also may get lost for unknown reasons.

A PR is on the way
