### ISSUE TITLE
Current subsite is not respected

### ISSUE THREAD

**Issue by phptek** [Firesphere/silverstripe-solr-search#199]
**Describe the bug**

X-post of: https://github.com/Firesphere/silverstripe-subsite-solr/issues/3

**To Reproduce**

See above (and linked Slack archive)

**Expected behavior**

See above (and linked Slack archive)

**Desktop (please complete the following information):**

See above (and linked Slack archive)

**Comment by Firesphere** [comment]
Confirmed and seems to only happen on Subsites submodule. I can't find what is actually going on, more debugging needed.

Added pipelines and labels, Needs to be resolved ASAP

**Comment by Firesphere** [comment]
Should be resolved in the latest master of Subsite submodule. Please re-open if the latest `dev-master` doesn't solve the problem?
