### ISSUE TITLE
On first load, there is no current controller

### ISSUE THREAD

**Issue by Firesphere** [Firesphere/silverstripe-solr-search#201]
**Describe the bug**
Unsure

**To Reproduce**
1. Clear the cache
2. Visit the website
3. See error

**Expected behavior**
No error

**Comment by Firesphere** [comment]
I am not sure if this is related to this module or not.

**Comment by Firesphere** [comment]
Confirmed. On load when the cache is empty, the DataObject is loaded before the controller, causing an error

**Comment by phptek** [comment]
I believe we have the same issue. I will get you a stscktrace out of Sentry if that's useful.

**Comment by Firesphere** [comment]
Yeah, emergency fix is adding 
```
if (!Controller::has_curr() {
return false;
}
```
At the top of `shouldPush` in `DataObjectExtension`

**Comment by Firesphere** [comment]
This "fix" is on master now too, you should not see it anymore when on master.

I need to think of a more proper implementation of this though.

**Comment by Firesphere** [comment]
Solved
