### ISSUE TITLE
Date range filters/excludes

### ISSUE THREAD

**Issue by kinglozzer** [Firesphere/silverstripe-solr-search#205]
Perhaps this is already possible, which I guess would make this a docs issue.. but I can’t spot how to add a date range filter.

I thought it would be possible with `->setExclude(['MyObject_DateField' => '[NOW TO *]'])`, but this seems to get escaped which then causes query errors.

I’m currently working around this with an extension:
```php
<?php

namespace App\Extensions\Indexes;

use Firesphere\SolrSearch\Queries\BaseQuery;
use SilverStripe\Core\Extension;
use Solarium\QueryType\Select\Query\FilterQuery;
use Solarium\QueryType\Select\Query\Query;

class DocumentIndexExtension extends Extension
{
    public function onBeforeSearch(BaseQuery $query, Query $clientQuery)
    {
        $clientQuery->addFilterQuery(
            new FilterQuery([
                'key' => 'exclude-Document_Embargo',
                'query' => '-Document_Embargo:[NOW TO *]'
            ])
        );
        $clientQuery->addFilterQuery(
            new FilterQuery([
                'key' => 'exclude-Document_Expiry',
                'query' => '-Document_Expiry:[* TO NOW]'
            ])
        );
    }
}

```

**Comment by Firesphere** [comment]
A cleaner way to do the query would be to use the include minimalsearch with `->greaterThanEqual(new \Datetime('1970-01-01'))`

There is indeed no current explicit date filter available, which could indeed be considered a bug.

**Comment by kinglozzer** [comment]
Just to summarise my Slack ramblings, my suggestion would be to allow `addFilter()`/`addExclude()` to accept `Minimalcode\Search\Criteria` objects as values and adjust `QueryComponentFilterTrait` to allow them. That would allow an API like:

```php
$criteria = Criteria::where('Document_Embargo')
    ->greaterThanEqual('NOW');
$query->addExclude('Document_Embargo', $criteria);
```

The changes to `QueryComponentFilterTrait` should be fairly simple to allow this too, for example an updated `buildExcludes` would look like:

```php
protected function buildExcludes(): void
{
    $filters = $this->query->getExclude();
    foreach ($filters as $field => $value) {
        if ($value instanceof Criteria) {
            $criteria = $value;
        } else {
            $value = is_array($value) ? $value : [$value];
            $criteria = Criteria::where($field)
                ->in($value)
                ->not();
        }

        $this->clientQuery->createFilterQuery('exclude-' . $field)
            ->setQuery($criteria->getQuery());
    }
}
```

**Comment by kinglozzer** [comment]
Some more investigation: what’s happening is that if you pass something that’s _already_ a Solr query component to `Criteria`, it gets escaped then and there by `Criteria`: https://github.com/minimalcode-org/search/blob/1.0.1/src/Minimalcode/Search/Criteria.php#L588-L615. So when `QueryComponentFactory` jumps in to escape the filters as usual, it’s actually escaping them for a second time.

As far as I can tell, that leaves two options.

1. The suggestion above
2. A third `boolean $escape = true` argument to `->addExclude()`, `addFilter()` etc. If `$escape = false;`, bypass `Criteria` and pass the value directly into the query `->setQuery($value)`

My vote is option 1, because:

- Option 2 is a bigger change. The arrays that hold excludes/filters would change from simple key=>value stores to nested arrays which hold the `$escape` flag. That makes it harder to use `->setExclude($array)` etc, as the array you have to construct is more complicated.
- I’m not sure how safely you can "negate" a filter for `->addExclude()`. Currently we call `->not()`, but if we’re not using `Criteria` objects we can’t do that. `$value = "-{$value}";` _might_ work, but I suspect the reality of Solr queries is more complex than that...

**Comment by Firesphere** [comment]
Closing this issue to be further discussed on the PR
