### ISSUE TITLE
Allow "blank" query term when searching

### ISSUE THREAD

**Issue by kinglozzer** [Firesphere/silverstripe-solr-search#209]
Essentially make it so that not setting a search term (`$query->addTerm()`) is equivalent to using `*:*`.

Using `$query->addTerm('*:*')` currently results in the term being escaped to `\*\:\*`.

Workaround is to add an extension to the index and use the following extension hook:

```php
<?php

namespace App\Extensions\Indexes;

use Firesphere\SolrSearch\Queries\BaseQuery;
use SilverStripe\Core\Extension;
use Solarium\QueryType\Select\Query\Query;

class MyIndexExtension extends Extension
{
    public function onBeforeSearch(BaseQuery $query, Query $clientQuery)
    {
        if ($clientQuery->getQuery() === '') {
            $clientQuery->setQuery('*:*');
        }
    }
}

```

**Comment by Firesphere** [comment]
Resolved in #211 , please continue discussion there
