### ISSUE TITLE
Unable to sort queries

### ISSUE THREAD

**Issue by kinglozzer** [Firesphere/silverstripe-solr-search#210]
Currently there doesn’t appear to be anything in `QueryComponentFactory` that copies the sort order over from the `BaseQuery` object to Solarium’s query object.

The [suggested format in the docs](https://github.com/Firesphere/silverstripe-solr-search/blame/52b1092d6e4ec9bb6202aefc42b45cdeda53bb4d/docs/03-Usage.md#L306-L311) (sorry for using blame view, apparently you can’t link to specific lines of markdown on Github without using it...) also appears to be incorrect, as solarium expects an array in the format of `<field> => <dir>` rather than an indexed array of strings which contain both the field name and direction.

As usual, my workaround is in the `onBeforeSearch()` hook:

```php
<?php

namespace App\Extensions\Indexes;

use Firesphere\SolrSearch\Queries\BaseQuery;
use SilverStripe\Core\Extension;
use Solarium\QueryType\Select\Query\Query;

class MyIndexExtension extends Extension
{
    public function onBeforeSearch(BaseQuery $query, Query $clientQuery)
    {
        $clientQuery->setSorts($query->getSort());
    }
}
```

The docs also need to be updated so they show sort examples in the following format:

```php
$baseQuery->setSort(['ObjectName_Date' => 'asc']);
```

**Comment by Firesphere** [comment]
Resolved in #211 , please continue discussion there
