### ISSUE TITLE
PHP8 support requires Solarium update

### ISSUE THREAD

**Issue by elliot-sawyer** [Firesphere/silverstripe-solr-search#247]
**Is your feature request related to a problem? Please describe.**
The version of Solarium used does not support PHP8. More recent versions do, and I've installed it using an alias `"solarium/solarium": "6.2.1 as 5.2.0"`

**Describe the solution you'd like**
Updating Solarium to ^6.0 allows the software to run on PHP8

**Comment by asecondwill** [comment]
plus 1

**Comment by asecondwill** [comment]
@elliot-sawyer  when you tried using an alias, didnt you get errors on the site as the interface has changed? 

 Solarium\Core\Client\Client::__construct(): Argument #1 ($adapter) must be of type Solarium\Core\Client\Adapter\AdapterInterface, array given, called in /var/www/html/vendor/firesphere/solr-search/src/Services/SolrCoreService.php on line 97

**Comment by asecondwill** [comment]
@Firesphere  - do you think this will happen? or have things moved on to FullTextSearch ?

**Comment by Firesphere** [comment]
Solarium 6 requires the adapter to be updated to a PSR adapter instead of the (currently used) Guzzle adapter.

This is covered in issue #217 , That needs to be completed before a switch to Solarium 6 can happen without any problems.

I've been working on it, but I don't think it's completed yet, see PR #221

**Comment by Firesphere** [comment]
> @Firesphere - do you think this will happen? or have things moved on to FullTextSearch ?

Heh, don't expect FullTextSearch to move anywhere any time soon...

**Comment by Firesphere** [comment]
@asecondwill @elliot-sawyer PR for this to get working is in Peer Review now, you can use it directly (with Solr9!) via branch `dev-hans/guzzle-to-psr`
