### ISSUE TITLE
Question: Does this module support indexing document contents (Files?)

### ISSUE THREAD

**Issue by josephlewisnz** [Firesphere/silverstripe-solr-search#252]
I've had a read of the docs and can't see anything specific about files/documents indexing content.

I understand a lot of search modules require you to manually extract and save into a db field or something along those lines.
eg 
https://github.com/silverstripe/silverstripe-textextraction

**Comment by Firesphere** [comment]
Text extraction is supported by Solr, I don't know however, how well it works.

For proper extraction, the text-extraction module should work with Apache Tika, as the contents are indeed then saved as a DB field.

Besides adding the extracted text as a field in your configuration, it works. Solr, nor the module, really cares if the content comes from a file or a db field as such.
