### ISSUE TITLE
Solr 8 Data Path

### ISSUE THREAD

**Issue by phptek** [Firesphere/silverstripe-solr-search#262]
**Describe the bug**

In a Docker setup (20.10.18) with `docker compose` (2.10.2)

* Module: `dev-primary`
* PHP: 7.4.27
* Solr: 8.11.2

Solr 8 uses as its data directory: `/var/solr/data`. Using the module as-is, with the config as follows and running `./vendor/bin/sake dev/tasks/SolrConfigureTask` I see the following error.

As part of `docker compose up -d` I'm copying the contents of `.solr` into the `solr` container's `/var/solr/data` directory, but despite this, Solr still complains.

**Config**
```
...
  store:
      mode: 'file'
      path: '.solr'
...
```

**Error**

```
error-log.ERROR: org.apache.solr.common.SolrException: Path /var/www/html/.solr/StarterSearchIndex must be relative to SOLR_HOME, SOLR_DATA_HOME coreRootDirectory. Set system property 'solr.allowPaths' to add other allowed paths. [] []
```

If memory serves, using the old silverstripe/fulltextsearch module, we had access to the `solr.xml` file where we might modify the `solr.allowPaths` setting. Not sure this is relevant though - read on:

It looks like the "path" config is used for _two_ things:

1. The name of the local directory where Solr config metadata is stored with/by the module
2. The name of the path to where Solr itself thinks its config is

Consequently, the core is not created and needs to be done manually.

I also noticed that if I tried to "cheat" and substitute ".solr" for a local dir called "/var/solr/data" in YML config and copy that contents into the container, it wouldn't work because of logic in the module that doesn't recognise nested directories.

For example setting "path" to "foo/bar" instead of ".solr", the module failed to created the directory "foo" altogether.

The solution is either to ensure that both can be _separately_ configured _or_ that nested directories are permitted ala:

```
...
  store:
      mode: 'file'
      path: '/var/solr/data'
...
```

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - OS: Ubuntu 20.04 Using Docker (see versions above)
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**

N/A

**Comment by phptek** [comment]
**Note:** Edit /opt/solr/bin/solr.sh and change `$SOLR_HOME`

**Comment by Firesphere** [comment]
> **Note:** Edit /opt/solr/bin/solr.sh and change `$SOLR_HOME`

As I told you in our company chat, indeed.

I am closing this issue and keep it in mind for next time I update the docs (Or you can make a PR if you feel like it, under [FAQ](https://github.com/Firesphere/silverstripe-solr-search/blob/primary/docs/15-Help/03-Known-issues.md) ).

This is an issue that's on Solr's end, something the module can't change. The security implementations done by the Solr team have limited the paths Solr can trawl through by default (good thing), causing anything that's even the slightest out of the ordinary to break (annoying thing).

The cross-permissions for the webserver to write the configuration, and Solr to be able to read the documentation have been a pain to deal with from the start, but it's sadly unavoidable.

**Comment by phptek** [comment]
While I forget the intracacies of my original problem, using Lando, I can map the `.solr/<core>` dir to `/var/solr/data/<core>` with the following:

```
  search:
    # Solr v7 is the only version supported by both Lando and firesphere/silverstripe-solr.
    # Solr v8 is mysteriously missing from the latter and the former does not support v9 without a custom Dockerfile
    type: solr:7
    core: MyCustomCore
    portforward: 33097
    overrides:
      volumes:
        - .solr/MyCustomCore:/var/solr/data/MyCustomCore
```

From what I know of Lando, I'm guessing it builds a ton of `docker-compose.yml` files and simply uses standard Docker volume mapping to make this work.
