### ISSUE TITLE
Remove guzzle6-adapter?

### ISSUE THREAD

**Issue by elliot-sawyer** [Firesphere/silverstripe-solr-search#263]
**Describe the bug**
The module will not install on a PHP 8.0.x installation without some persuasion

**To Reproduce**
1. Try to install `composer require firesphere/solr-search`
2. Observe `php-http/guzzle6-adapter[v2.0.0, ..., v2.0.1] require php ^7.1 -> your php version (8.0.25) does not satisfy that requirement.`
3. Install this instead: `composer require php-http/guzzle6-adapter 2.0.2` (this specific tag added "[untested](https://github.com/php-http/guzzle6-adapter#guzzle-6-http-adapter)" PHP8.0 support)
4. Then install Guzzle 7, as 6 `composer require guzzlehttp/guzzle 7.5.0 as 6.5.7`
5. Finally `composer require firesphere/solr-search 2.0.0-rc1`

**Expected behavior**
I should be able to install the module when Guzzle 7 is present, but the project forces the install of 6 because the guzzle6-adapter is pulled in as a dependency. If the project can use 7 (as indicated in the requirements), the parent project should be responsible for using the guzzle6-adapter if they want to use 6

**Context**
Using php:8.0-apache-focal container

**Comment by Firesphere** [comment]
Yes, RC-1 and `dev-primary` have this requirement replaced with
`    "guzzlehttp/guzzle": "^6.3|^7",`
This should fix the problem?

We can't discard Guzzle entirely, as it's still needed for the PostConfig store.

Given that the latest version, 2.x-rc1 is a breaking change (we stop supporting Solr < 6, although it does still work), I'll probably release it soon.

**Comment by Firesphere** [comment]
The guzzle adapter is still needed, but as guzzle7-adapter.

It's a bit frustrating, but it's needed still.
