### ISSUE TITLE
WebDav store

### ISSUE THREAD

**Issue by Firesphere** [Firesphere/silverstripe-solr-search#47]
Preferably avoided, but if needed it can be added.

**Comment by Firesphere** [comment]
Also, WebDav is very CWP specific, it might be better off in a CWP Search module instead. The store to use will become configurable anyway

**Comment by Firesphere** [comment]
Yep, this is a CWP type task that could work with an extension instead of being part of this core module @chillu

**Comment by chillu** [comment]
> WebDav is very CWP specific

It's not actually used in CWP :) There's a custom proxy which allows writing of `solrconfig.xml`
