### ISSUE TITLE
Geospatial search

### ISSUE THREAD

**Issue by Firesphere** [Firesphere/silverstripe-solr-search#60]
Adding geospatial awareness to the search would be great. Solr can do this easily and thereby reducing the need for PHP overhead

**Comment by Firesphere** [comment]
Currently not a feature of FTS.

Can be achieved through simple customisations and reading the Solarium docs.

Might be added later, but it's a Nice to Have

**Comment by elliot-sawyer** [comment]
If you want a dataset to work with, my module elliot-sawyer/nzstreets wraps a DataObject around ~2m LINZ Street addresses.
* https://github.com/elliot-sawyer/silverstripe-nzstreets
* https://data.linz.govt.nz/layer/53353-nz-street-address/data/

The set contains actual WKT point data for GIS applications, as well as the traditional lon/lat coordinates

**Comment by Firesphere** [comment]
Interesting usecase!! Won't make it in to release 1, but definitely a good test env!

**Comment by Firesphere** [comment]
Resolved by @TractorCow his fix to allow Criteria to be passed in to the query build.

**Comment by tractorcow** [comment]
I did? Cool :) I forgot about it entirely haha.
