### ISSUE TITLE
Don't index "showInSearch = false"

### ISSUE THREAD

**Issue by Firesphere** [Firesphere/silverstripe-solr-search#86]
The indexing is not making a difference between `showInSearch` flag at the moment. This needs to be addressed asap.

**Comment by michalkleiner** [comment]
I guess that is just one aspect of the wider "search variants" area. How do you plan to handle other variants like language-based, subsite-ID-based etc.?

**Comment by Firesphere** [comment]
Subsites already works. Languages would be a choice plus a default filter on the implementation side.
Could add a default for Fluent though.
